### ISSUE TITLE
Colored Track?

### ISSUE THREAD

**Issue by fabeluna** [buzinas/simple-scrollbar#5]
Hello,
awesome Plugin! Is it also possible to show and color the scrollbars track?

Thanks,
Leonie

**Comment by buzinas** [comment]
Unfortunately this is a simple version, so it's not possible.

But feel free to take it and modify it the way you want :)

**Comment by kf6kjg** [comment]
A little custom CSS can go a long way for customizing the scroll bar, eg:
```
.ss-scroll {
	background-color: blue;
	opacity: 1;
}
```

However, as buzinas said, there's no way to color the track because there isn't currently any track: the "track" is formed from a right padding area and therefore cannot be independently colored.

(When I was reading around trying to see how to color the bar I thought this question was about that concept - instead it was about the track, so I decided to post this comment to clarify it for anyone else after me.)
